ClientMDA/Models/ErrorViewModel.cs
using System;

namespace ClientMDA.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClientMDA/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class CommentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClientMDA/Controllers/HomePageController.cs
using ClientMDA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class HomePageController : Controller
    {
        private readonly ILogger<HomePageController> _logger;

        public HomePageController(ILogger<HomePageController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClientMDA/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class MemberController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClientMDA/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class ShoppingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClientMDA/Controllers/TheaterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class TheaterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClientMDA/Controllers/TicketingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientMDA.Controllers
{
    public class TicketingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MovieInfoIndex()
        {
            return View();
        }
        public IActionResult MovieInfoIndex2()
        {
            return View();
        }

        public IActionResult MovieInfoIndex3()
        {
            return View();
        }

        public IActionResult Cinema()
        {
            return View();
        }

        public IActionResult SeatMap()
        {
            return View();
        }

        public IActionResult PaymentWeb()
        {
            return View();
        }

        public IActionResult PaymentWeb2()
        {
            return View();
        }

        public IActionResult PaymentWeb3()
        {
            return View();
        }

        public IActionResult Cube()
        {
            return View();
        }
    }
}

ClientMDA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClientMDA/Views/HomePage/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

ClientMDA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>M.D.A.觀享時刻</title>
    <meta name="author" content="MSIT143 01陳苡錚 06王婷薇 11廖家毅 13李沛軒 16洪暐婷 18游曉雯 20鄭凱" />
    <meta name="keywords" content="M.D.A.觀享時刻,M.D.A.,MDA,觀享時刻,電影訂票,電影評論,訂票,評論,電影,電視劇,動畫" />
    <meta name="date" content="2022/06/15" />
    <meta name="description" content="M.D.A. 為 Movie, Drama, Anime 的縮寫。希望藉由這個整合平台，讓最完整的電影、電視劇及動畫相關資訊都能快速方便的被使用者查找、觀賞及討論。" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/plyr.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">






</head>
<body>
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="./index.html">
                            <img src="img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active">
                                    <a href="./index.html">訂票</a>
                                    <ul class="dropdown">
                                        <li><a href="./categories.html">本週新片</a></li>
                                        <li><a href="./anime-details.html">上映中</a></li>
                                        <li><a href="./anime-watching.html">即將上映</a></li>
                                        <li><a href="./blog-details.html">歷年電影</a></li>
                                        <li><a href="./blog-details.html">電影排行</a></li>
                                        <li><a href="./blog-details.html">我的評論</a></li>
                                        
                                    </ul>
                                </li>

                                <li>
                                    <a href="./categories.html">電影<span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">

                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="MovieInfoIndex">我要訂票</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="MovieInfoIndex2">我也要訂票</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="MovieInfoIndex3">我還要訂票</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="SeatMap">我要座位</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="PaymentWeb">我要付錢</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="PaymentWeb2">我要也付錢</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="PaymentWeb3">我真的付錢</a></li>
                                        <li><a asp-area="" asp-controller="Ticketing" asp-action="Cube">方塊</a></li>
                                        <li><a href="./categories.html">本週新片</a></li>
                                        <li><a href="./anime-details.html">上映中</a></li>
                                        <li><a href="./anime-watching.html">即將上映</a></li>
                                        <li><a href="./blog-details.html">歷年電影</a></li>
                                        <li><a href="./blog-details.html">電影排行</a></li>
                                        <li><a href="./blog-details.html">我的評論</a></li>
                                    </ul>
                                </li>
                                <li><a href="./anime-details.html">影評</a></li>  <!--./blog.html-->
                                <li><a href="#">商城</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        <a href="./login.html"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap">
                <div class="slicknav_menu">
                    <a href="#" aria-haspopup="true" role="button" tabindex="0" class="slicknav_btn slicknav_collapsed"><span class="slicknav_menutxt">MENU</span><span class="slicknav_icon"><span class="slicknav_icon-bar"></span><span class="slicknav_icon-bar"></span><span class="slicknav_icon-bar"></span></span></a><nav class="slicknav_nav slicknav_hidden" aria-hidden="true" role="menu" style="display: none;">
                        <ul>
                            <li><a href="./index.html" role="menuitem">Homepage</a></li>
                            <li class="slicknav_collapsed slicknav_parent">
                                <a href="#" role="menuitem" aria-haspopup="true" tabindex="-1" class="slicknav_item slicknav_row">
                                    <span class="slicknav_arrow">►</span>
                                </a><ul class="dropdown slicknav_hidden" role="menu" aria-hidden="true" style="display: none;">
                                    <li><a href="./categories.html" role="menuitem" tabindex="-1">Categories</a></li>
                                    <li><a href="./anime-details.html" role="menuitem" tabindex="-1">Anime Details</a></li>
                                    <li><a href="./anime-watching.html" role="menuitem" tabindex="-1">Anime Watching</a></li>
                                    <li><a href="./blog-details.html" role="menuitem" tabindex="-1">Blog Details</a></li>
                                    <li><a href="./signup.html" role="menuitem" tabindex="-1">Sign Up</a></li>
                                    <li><a href="./login.html" role="menuitem" tabindex="-1">Login</a></li>
                                </ul>
                                <link href="~/css/site.css" rel="stylesheet" />
                            </li>
                            <li class="active"><a href="./blog.html" role="menuitem">Our Blog</a></li>
                            <li><a href="#" role="menuitem">Contacts</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <hr />
        <footer class="footer">
            <div class="page-up">
                <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="footer__logo">
                            <a href="./index.html"><img src="img/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="footer__nav">
                            <ul>
                                <li class="active"><a href="./index.html">Homepage</a></li>
                                <li><a href="./categories.html">Categories</a></li>
                                <li><a href="./blog.html">Our Blog</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            M.D.A. Co., Ltd. All rights reserved.<br /><a href="https://colorlib.com" target="_blank">M.D.A.</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>

                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery-3.4.1.min.js"></script>
</body>
</html>

ClientMDA/Views/Ticketing/Cube.cshtml
@{

}

    <meta charset="utf-8">
    <title>Swiper demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css">

    <!-- Demo styles -->
    <style>
        html,
        body {
            position: relative;
            height: 100%;
        }

        body {
            background: #eee;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #000;
            margin: 0;
            padding: 0;
        }

        .swiper {
            width: 300px;
            height: 300px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-left: -150px;
            margin-top: -150px;
        }

        .swiper-slide {
            background-position: center;
            background-size: cover;
        }

            .swiper-slide img {
                display: block;
                width: 100%;
            }
    </style>

<section>
    <div class="swiper mySwiper swiper-cube swiper-3d swiper-initialized swiper-horizontal swiper-pointer-events swiper-watch-progress">
        <div class="swiper-wrapper" id="swiper-wrapper-2534bcd138415866" aria-live="polite" style="cursor: grab; transform-origin: 50% 50% -150px; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(-180deg); --swiper-cube-translate-z:0px; transition-duration: 0ms;">
            <div class="swiper-slide" role="group" aria-label="1 / 4" style="width: 300px; transform: rotateX(0deg) rotateY(0deg) translate3d(0px, 0px, 0px); transition-duration: 0ms;">
                <img src="~/images/Ticketing/1.jpg">
                <div class="swiper-slide-shadow-left" style="opacity: 0;"></div><div class="swiper-slide-shadow-right" style="opacity: 1;"></div>
            </div>
            <div class="swiper-slide swiper-slide-prev" role="group" aria-label="2 / 4" style="width: 300px; transform: rotateX(0deg) rotateY(90deg) translate3d(0px, 0px, 0px); transition-duration: 0ms;">
                <img src="~/images/Ticketing/2.jpg">
                <div class="swiper-slide-shadow-left" style="opacity: 0;"></div><div class="swiper-slide-shadow-right" style="opacity: 1;"></div>
            </div>
            <div class="swiper-slide swiper-slide-visible swiper-slide-active" role="group" aria-label="3 / 4" style="width: 300px; transform: rotateX(0deg) rotateY(180deg) translate3d(300px, 0px, 300px); transition-duration: 0ms;">
                <img src="~/images/Ticketing/3.jpg">
                <div class="swiper-slide-shadow-left" style="opacity: 0;"></div><div class="swiper-slide-shadow-right" style="opacity: 0;"></div>
            </div>
            <div class="swiper-slide swiper-slide-next" role="group" aria-label="4 / 4" style="width: 300px; transform: rotateX(0deg) rotateY(270deg) translate3d(-300px, 0px, 900px); transition-duration: 0ms;">
                <img src="~/images/Ticketing/4.jpg">
                <div class="swiper-slide-shadow-left" style="opacity: 1;"></div><div class="swiper-slide-shadow-right" style="opacity: 0;"></div>
            </div>
            <div class="swiper-cube-shadow" style="height: 300px; transform: translate3d(0px, 170px, -150px) rotateX(90deg) rotateZ(0deg) scale(0.94);"></div>
        </div>
        <div class="swiper-pagination swiper-pagination-bullets swiper-pagination-horizontal"><span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet swiper-pagination-bullet-active" aria-current="true"></span><span class="swiper-pagination-bullet"></span></div>
        <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>
    </div>
</section>

    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script>
      var swiper = new Swiper(".mySwiper", {
        effect: "cube",
        grabCursor: true,
        cubeEffect: {
          shadow: true,
          slideShadows: true,
          shadowOffset: 20,
          shadowScale: 0.94,
        },
        pagination: {
          el: ".swiper-pagination",
        },
      });
    </script>

ClientMDA/Views/Ticketing/MovieInfoIndex2.cshtml
@{

}

<link href="~/assets/img/favicon.png" rel="icon">
<link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
<link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
<link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
<link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
<link href="~/assets/css/main.css" rel="stylesheet">

<style>
    html {
        background-color: #070720;
    }

    body {
        background-color: #070720;
    }

    .Screen {
        font-family: Montserrat, "Noto Sans TC", "Microsoft JhengHei", sans-serif !important;
        position: relative;
        width: 100%;
        min-height: 100vh;
        height: 100vh;
        background-color: #070720;
        z-index: 2000;
        padding-bottom: 100px;
        overflow: auto;
        height: calc(100vh - 130px);
        float: none;
        width: 100%;
        margin: 5px auto;
        overflow-y: auto;
    }

    .dyOReL {
        clear: both;
    }

    .Screen .wrapper {
        max-width: 1200px;
        width: 100%;
        margin: auto;
        text-align: center;
        position: relative;
        justify-content: space-between;
    }

        .Screen .wrapper .north {
            width: 35%;
        }

        .Screen .wrapper .space {
            width: 20%;
            height: 5vh;
        }

        .Screen .wrapper .loc-part {
            min-width: 180px;
            width: 22%;
            min-height: 80vh;
            display: inline-flex;
            -webkit-box-pack: start;
            place-content: flex-start;
            flex-wrap: wrap;
            vertical-align: top;
        }

            .Screen .wrapper .loc-part .big-title {
                width: 100%;
                font-size: 1.375rem;
                color: rgb(158, 158, 158);
                font-weight: 300;
                text-align: left;
                height: 50px;
                float: left;
                margin: 0px;
            }

            .Screen .wrapper .loc-part .cinema {
                width: 100%;
                color: rgb(255, 255, 255);
                font-weight: 300;
                text-align: left;
                cursor: pointer;
                height: 50px;
            }

                .Screen .wrapper .loc-part .cinema:hover {
                    color: rgb(220, 220, 220);
                    font-size: 1.1rem;
                }
</style>

<main id="main" data-aos="fade" data-aos-delay="1500">
    <section class="pricing" id="pricing">
        <div class="Screen">
            <div class="wrapper">
                <div class="space"></div>
                <div class="loc-part north">
                    <h3 class="big-title">北區</h3>
                    <div class="commonStyled__Clearfix-sc-kt5vy-2 dyOReL"></div>
                    <div class="cinema">台北信義威秀影城</div>
                    <div class="cinema">台北美麗華大直影城</div>
                    <div class="cinema">台北京站威秀影城</div>
                    <div class="cinema">板橋大遠百威秀影城</div>
                    <div class="cinema">喜樂時代影城南港店</div>
                    <div class="cinema">台北in89豪華數位影城</div>
                    <div class="cinema">喜滿客絕色影城</div>
                    <div class="cinema">台北獅子林新光影城</div>
                    <div class="cinema">林口MITSUI OUTLET PARK威秀影城</div>
                    <div class="cinema">台北樂聲影城</div>
                    <div class="cinema">喜樂時代影城永和店</div>
                    <div class="cinema">台北真善美劇院</div>
                    <div class="cinema">梅花數位影城</div>
                    <div class="cinema">哈拉影城</div>
                    <div class="cinema">台北新民生戲院</div>
                    <div class="cinema">花蓮新天堂樂園威秀影城</div>
                    <div class="cinema">中和環球威秀影城</div>
                    <div class="cinema">MUVIE CINEMAS台北松仁威秀</div>
                    <div class="cinema">台北天母新光影城</div>
                </div><div class="loc-part ">
                    <h3 class="big-title">桃竹苗</h3>
                    <div class="commonStyled__Clearfix-sc-kt5vy-2 dyOReL"></div>
                    <div class="cinema">桃園青埔新光影城</div>
                    <div class="cinema">喜樂時代影城桃園A19店</div>
                    <div class="cinema">桃園in89統領影城</div>
                    <div class="cinema">桃園統領威秀影城</div>
                    <div class="cinema">新竹大遠百威秀影城</div>
                    <div class="cinema">頭份尚順威秀影城</div>
                    <div class="cinema">新竹巨城威秀影城</div>
                </div>
                <div class="loc-part ">
                    <h3 class="big-title">中區</h3><div class="commonStyled__Clearfix-sc-kt5vy-2 dyOReL"></div>
                    <div class="cinema">台中豐原in89豪華影城</div>
                    <div class="cinema">台中大遠百威秀影城</div>
                    <div class="cinema">台中大魯閣新時代威秀影城</div>
                    <div class="cinema">台中Tiger City威秀影城</div>
                    <div class="cinema">台中中港新光影城</div>
                </div>
                <div class="loc-part ">
                    <h3 class="big-title">南區及離島</h3>
                    <div class="commonStyled__Clearfix-sc-kt5vy-2 dyOReL"></div>
                    <div class="cinema">台南南紡威秀影城</div><div class="cinema">台南大遠百威秀影城</div>
                    <div class="cinema">台南FOCUS威秀影城</div><div class="cinema">台南西門新光影城</div>
                    <div class="cinema">台南真善美劇院</div><div class="cinema">高雄大遠百威秀影城</div>
                    <div class="cinema">高雄in89駁二電影院</div><div class="cinema">中影屏東影城</div>
                    <div class="cinema">澎湖in89豪華影城</div>
                </div>
            </div>
        </div>
    </section>

</main>
<div id="preloader">
    <div class="line"></div>
</div>



<script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/assets/vendor/aos/aos.js"></script>
<script src="~/assets/vendor/php-email-form/validate.js"></script>
<script src="~/assets/js/main.js"></script>

ClientMDA/Views/Ticketing/MovieInfoIndex3.cshtml
@{

}

<link href="~/assets/css/main.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css" />
<style>

    html,body,header {
        background-color: #070720;
    }

    h4 {
        color: whitesmoke;
        font-family: "標楷體";
    }

        h4:hover {
            color: #6C6C6C;
            font-size: 150%;
            cursor: pointer;
        }

    .swiper {
        width: 100%;
        height: 480px;
    }

    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }

        .swiper-slide img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
    .col-lg-4{
        padding:5px;
    }

    .card{
        width:100px;
        height:500px;
    }
</style>

<body>
    <section class="container">
        <div class="align-content-xl-start">
            <h2 class="text-bg-primary fa-space-awesome" style="padding-bottom:2%;color:whitesmoke">現正熱門</h2>
        </div>
        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide"><img src="~/images/Ticketing/1.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/2.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/3.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/4.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/5.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/6.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/1.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/2.jpg" /></div>
                <div class="swiper-slide"><img src="~/images/Ticketing/3.jpg" /></div>
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
        </div>
    </section>

    <section class="container">
        <div class="align-content-xl-start">
            <h2 class="text-bg-primary fa-space-awesome" style="padding-bottom:2%;padding-top:3%;color:whitesmoke">所有電影</h2>
        </div>
        <div class="row gy-4 gx-lg-5">

            @{
                for (int i = 0; i < 50; i++)
                {

                    <div class="col-lg-4">
                        <div class="pricing-item d-flex justify-content-between">
                            <h4>範例電影名稱</h4>
                        </div>
                    </div>

                }
            }
        </div>
    </section>
    <section>
        <div class="align-content-xl-start">
            <h2 class="text-bg-primary fa-space-awesome" style="padding-bottom:2%;padding-top:3%;color:whitesmoke">你可能喜歡</h2>
        </div>


        <div class="swipercard mySwipercard">
            <div class="swiper-wrapper">
                <div class="swiper-slide card"><img src="~/images/Ticketing/1.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/2.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/3.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/4.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/5.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/6.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/1.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/2.jpg" /></div>
                <div class="swiper-slide card"><img src="~/images/Ticketing/3.jpg" /></div>
            </div>
        </div>
    </section>

    <div id="preloader">
        <div class="line"></div>
    </div>




    <script src="~/assets/js/main.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script>
        var swiper = new Swiper(".mySwiper", {
            slidesPerView: 3,
            spaceBetween: 30,
            slidesPerGroup: 3,
            loop: true,
            loopFillGroupWithBlank: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
        });

            var swipercard = new Swiper(".mySwipercard", {
                effect: "cards",
            grabCursor: true,
          });
    </script>
</body>

ClientMDA/Views/Ticketing/PaymentWeb3.cshtml
@{

}

<style>
    section {
        text-align:center;
    }

    .px-3 h1 {
        color:whitesmoke;
    }

    .px-3 p {
        color:whitesmoke;
    }
</style>

<section>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main class="px-3">
            <h1>感謝你的購買</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
                <a href="#" class="btn btn-lg btn-primary fw-bold border-2 bg-black">確定</a>
            </p>
        </main>
    </div>
</section>